[project]
name = "manage_shipment"
authors = [{name = "Sundaram Technologies", email = "support@sundaramtech.com"}]
description = "Shipment and domestic courier tracking for ERPNext"
requires-python = ">=3.10"
readme = "README.md"
dynamic = ["version"]
license = {text = "MIT"}

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

[tool.bench.frappe-dependencies]
frappe = ">=16.0.0-dev,<17.0.0"
